version: '3'
services:
  # web:
  #     build: .
      # command: bash ./mo.sh
  wordpress:
    image: wordpress:5.2.4
    container_name: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      # WP_URL: localhost
      # WP_TITLE: WordPress Demo
      # WP_ADMIN_USER: admin_user
      # WP_ADMIN_PASSWORD: secrett
      # WP_ADMIN_EMAIL: test@test.com
    ports:
      - 8080:80
      - 443:443
  db:
    image: mysql:8
    container_name: mysql
    # restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: localhost
      MYSQL_ROOT_PASSWORT: password

 
